// src/pages/Mine/index.vue
<template>
  <div class="mine w-100 overflow-y-scroll">
    <div class="mine-top bg-[#0b75ff] w-full px-[0px]">
      <div class="topbar-container">
        <div class="van-safe-area-top">
          <div class="topbar-content-view flex justify-between items-end">
            <div
              v-for="item in topBarItemList"
              :key="item.icon"
              :class="item.icon === 'logo' ? 'logo-container' : item.icon"
              @click="changeRoute(item.routePath)"
            >
              <template v-if="item.title">
                <!-- <div :class="item.icon"></div> -->
                <!-- <img :src="homeTopLogo" class="home-top-logo" /> -->
                <div class="text-logo">我的</div>
              </template>

              <div
                v-if="item.icon === 'message' && unReadCount"
                class="unread-sign"
              >
                {{ unReadCount }}
              </div>
            </div>
          </div>
        </div>
        <div class="mt-[30px] flex items-center justify-between">
          <div class="flex items-center">
            <div class="avatar relative overflow-hidden rounded-md bg-[#fff]">
              <div
                class="avatar1"
                v-if="!authStore?.userInfo?.headimg"
              ></div>
              <img
                v-else
                class="w-[110px] h-[110px] block"
                :src="imgServerUrl + authStore?.userInfo?.headimg"
                alt=""
              />
              <div
                class="mask w-full bg-black/50 absolute bottom-0 left-0 h-[30px] flex items-center"
              >
                <div class="camera mx-auto"></div>
              </div>
              <input
                className="avatar-input absolute top-0 left-0 w-full h-full opacity-0 z-2"
                type="file"
                accept="image/*"
                @change="afterRead"
                @click="onAvatarClick"
              />
            </div>
            <div class="ml-[7.5px]">
              <div class="text-[30px] text-white flex items-center mb-[10px]">
                {{ authStore?.userInfo?.nickname }}
                <div
                  class="edit ml-[10px] scale-[0.8]"
                  @click="handleEditNicknameDialog(true)"
                ></div>
              </div>
              <div class="text-[#94c3ff] text-[24px] flex items-center">
                {{ authStore?.userInfo?.username }}
                <img
                  :src="copyIcon"
                  alt=""
                  class="w-[30px] ml-[10px]"
                  @click="copy(authStore?.userInfo?.username)"
                />
              </div>
            </div>
          </div>
          <div @click="goFundingDetails">
            <div class="text-[24px] text-[#94c3ff] text-right">余额></div>
            <div class="text-[30px] font-bold text-white">
              {{ Number(current_coin?.coincash).toTruncFixed(3) }}
              <span class="text-[24px] text-white font-normal">{{ current_coin?.coin_unit }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mine-content p-[24px] bg-[#ebf1f6]">
      <div
        :key="entry.title"
        class="entry-row bg-white rounded-sm w-full h-[82px] px-[24px] flex items-center justify-between"
        v-for="entry in entry_list_1"
        @click="entry.action"
      >
        <div class="text-[30px] text-[#13161b] flex items-center">
          <div :class="`${entry.icon} mr-1`"></div>
          {{ entry.title }}
        </div>
        <div :class="`text-[24px] ${entry.status_text?.color} flex items-center`">
          {{ entry.status_text?.text }}
          <div class="chervon-right ml-1"></div>
        </div>
      </div>

      <div class="text-[24px] text-[#787f8c] mt-2 mb-[7.5px] ml-1">收款及支付方式</div>
      <div class="bg-white rounded-sm">
        <div
          :key="entry.title"
          class="entry-row w-full h-[82px] px-[24px] flex items-center justify-between"
          v-for="entry in entry_list_2"
          @click="entry.action"
        >
          <div class="text-[30px] text-[#13161b] flex items-center">
            <div :class="`${entry.icon} mr-1`"></div>
            {{ entry.title }}
          </div>
          <div :class="`text-[24px] ${entry.status_text?.color} flex items-center`">
            {{ entry.status_text?.text }}
            <div class="chervon-right ml-1"></div>
          </div>
        </div>
      </div>

      <div class="text-[24px] text-[#787f8c] mt-2 mb-[7.5px] ml-1">账号安全</div>
      <div class="bg-white rounded-sm">
        <div
          :key="entry.title"
          class="entry-row w-full h-[82px] px-[24px] flex items-center justify-between"
          v-for="entry in entry_list_3"
          @click="entry.action"
        >
          <div class="text-[30px] text-[#13161b] flex items-center">
            <div :class="`${entry.icon} mr-1`"></div>
            {{ entry.title }}
          </div>
          <div class="text-[24px] text-[#787f8c] flex items-center">
            {{ entry.status_text }}
            <div class="chervon-right ml-1"></div>
          </div>
        </div>
      </div>

      <div class="text-[24px] text-[#787f8c] mt-2 mb-[7.5px] ml-1">其他</div>
      <div class="bg-white rounded-sm">
        <div
          :key="entry.title"
          class="entry-row w-full h-[82px] px-[24px] flex items-center justify-between"
          v-for="entry in entry_list_4"
          @click="entry.action"
        >
          <div class="text-[30px] text-[#13161b] flex items-center">
            <img
              v-if="entry.img_src"
              :src="entry.img_src"
              alt=""
              class="w-[40px] mr-1"
            />
            <div
              v-else
              :class="`${entry.icon} mr-1`"
            ></div>
            {{ entry.title }}
          </div>
          <div class="text-[24px] text-[#787f8c] flex items-center">
            {{ entry.status_text }}
            <div class="chervon-right ml-1"></div>
          </div>
        </div>
      </div>
    </div>

    <van-dialog
      v-model:show="dialog.show"
      :title="dialog.data.title"
      theme="round-button"
      className="dialog-msg"
      @confirm="onCloseDialog"
    >
      <i
        class="icon-close block close-dark"
        @click="onCloseDialog"
      ></i>

      <div class="add-time">{{ dialog.data.add_time }}</div>
      <div
        class="content"
        v-html="dialog.data.content"
      ></div>

      <template #footer>
        <div
          class="btn-confirm flex items-center justify-center"
          @click="onCloseDialog"
        >
          我知道了
        </div>
      </template>
    </van-dialog>
    <van-dialog
      v-model:show="isEditNicknameDialog"
      title="昵称修改"
      confirmButtonText="提交"
      theme="round-button"
      className="dialog-bulletin"
      @confirm="() => editNickname()"
    >
      <i
        class="icon-close close-dark block"
        @click="handleEditNicknameDialog(false)"
      ></i>
      <div>
        <van-field
          v-model="edit_nickname"
          placeholder="昵称限制3-8位长度"
        />
      </div>
    </van-dialog>
    <!-- <van-dialog v-model:show="dialogContent.show" :title="dialogContent.title" theme="round-button"
      :className="['dialog-deal']" :confirmButtonText="dialogContent.confirmButtonText" @confirm="onConfirm">
      <i class="icon-close block close-dark" @click="onClose"></i>
      <div class="flex flex-col items-center justify-between">
        <img :src="dialogContent.img" :class="!authStore?.userInfo.verified_status ? 'verifi-id' : 'add-card'" />
        <div class="content text-center">{{ dialogContent.content }}</div>
      </div>
    </van-dialog> -->
  </div>
</template>

<script setup lang="ts">
import { useAuthStore, useEntryStore } from '@/store'
import { onMounted, ref, computed, reactive } from 'vue'
import { useCoinBuySellStore } from '@/store/modules/coinBuySell'
import { useRouter } from 'vue-router'
import { uploadImgApi } from '@/apis/common'
import { updateUserInfoApi } from '@/apis/user'
import creditImg from '@/assets/images/mine/credit.png'
import { IMessage } from '@/store/types/article'
import { userMessageDetailsApi, userMessageListApi } from '@/apis/article'
import { showToast } from 'vant'
import { useAppBar } from '@/components/AppBar/useAppBar'
// import verifyID from '@/assets/images/common/ID-verify.png'
// import passIcon from '@/assets/images/common/key.png'
import copyIcon from '@/assets/images/mine/copy.png'

// import homeTopLogo from '@/assets/images/home_top_logo.png'
// import addCard from '@/assets/images/common/add-card.png'
import info from '@/assets/images/common/info.png'
import success from '@/assets/images/common/success.png'
import verified from '@/assets/images/common/verified.png'
import { storeToRefs } from 'pinia'
import clipboard3 from 'vue-clipboard3'

useAppBar({ mode: 'dark' })

const showInfoToast = (title: string) => {
  return showToast({
    message: title,
    icon: info
  })
}
const onAvatarClick = function (e: Event) {
  if (authStore?.editreview?.headimg?.status === -1) {
    e.preventDefault()
    return showToast({
      message: '头像正在审核中，请等待',
      icon: info
    })
  }
}
const showSuceedToast = (title: string) => {
  return showToast({
    message: title,
    icon: success
  })
}

const topBarItemList = [
  {
    // routePath: '/iframe-page/customer-service',
    routePath: '/iframe-page/third?url=customer-service',
    icon: 'customer-service'
  },
  {
    routePath: '',
    icon: 'logo',
    title: 'GDPAY'
  },
  {
    // routePath: '/iframe-page/tutorial',
    routePath: '/iframe-page/third?url=' + import.meta.env.VITE_APP_TUTORIAL_URL + '?from=gdpay_h5',
    icon: 'help'
  },
  {
    routePath: '/message',
    icon: 'message'
  }
]

const router = useRouter()
const changeRoute = (path: string) => {
  router.push(path)
}

const { toClipboard } = clipboard3()
const copy = async (text: any) => {
  try {
    await toClipboard(text)
    // showToast('复制成功');
    showToast({
      message: '复制成功',
      icon: verified,
      iconSize: '48px'
    })
  } catch (error) {
    // showToast('复制失败!!');
    showToast({
      message: '复制失败!!',
      icon: verified
    })
  }
}

const entryStore = useEntryStore()
const imgServerUrl = entryStore.imgServerUrl
const authStore = useAuthStore()
const { getUserCoin } = authStore
const { coins } = storeToRefs(authStore)
const getUserCoinData = async (isReq: boolean = false) => {
  try {
    window.log('用户积分信息', coins.value, isReq)

    if (coins.value.length && !isReq) {
      return
    }

    const res = await getUserCoin({})
    window.log('用户积分信息2', res)
  } catch (error) {
    console.error(error)
  }
}
// 是否实名认证 0 否 1 成功 2待审核 3 拒绝’
// authStore?.userInfo?.verified_status
const isLogin = !!authStore.token

const coin = useCoinBuySellStore()
const { withdrawddresslist, getWithdrawddresslist } = coin

const tutorial_link = ref(import.meta.env.VITE_APP_TUTORIAL_URL)
const current_coin = ref({
  mtype: 0,
  coin_name: '',
  coin_unit: 'GDB',
  coincash: '',
  available_coincash: '',
  status: 0,
  wallet_type: '',
  service_fee: ''
})
const getMineInfo = async () => {
  try {
    const coin = authStore?.coins.filter(coin => coin?.coin_unit === 'GDB')?.[0]
    await authStore?.getUserInfo()
    console.log(authStore.userInfo.is_set_paypassword, 'authStore.userInfo.is_set_paypassword')
    current_coin.value = coin
    getUserCoinData()
    getDialogMessage()
  } catch (e) {
    console.log(e)
  }
}

const verifyStatusText = () => {
  // 0 未认证 1 已认证   2审核中   3 请重新认证   4禁止认证
  if (authStore?.userInfo?.verified_status === 0) {
    return { text: '未认证', color: 'text-[#ff0000]' }
  } else if (authStore?.userInfo?.verified_status === 3) {
    return { text: '请重新认证', color: 'text-[#ff0000]' }
  } else if (authStore?.userInfo?.verified_status === 4) {
    return { text: '禁止认证', color: 'text-[#ff0000]' }
  } else if (authStore?.userInfo?.verified_status === 1) {
    return { text: '已认证', color: 'text-[#58cf00]' }
  } else if (authStore?.userInfo?.verified_status === 2) {
    return { text: '审核中', color: 'text-[#777]' }
  } else return { text: '', color: 'text-[#777]' }
}

const bind_bank = ref({})
const bind_wechat = ref({})
const bind_alipay = ref({})

const bankCardStatusText = (bank: any) => {
  //   status   DEFAULT '1' COMMENT '1启用  2禁用   -1审核中 ',
  if (bank?.status === 1) {
    return {
      text: '已绑定',
      color: 'text-[#58cf00]'
    }
  }

  if (!bank?.status) {
    return {
      text: '未绑定',
      color: 'text-[#ff0000]'
    }
  }

  if (bank?.status === 2) {
    return {
      text: '已拒绝',
      color: 'text-[#ff0000]'
    }
  }

  if (bank?.status === -1) {
    return {
      text: '审核中',
      color: 'text-[#777]'
    }
  }
}

const payPassStatusText = (is_set_pass: number) => {
  return is_set_pass === 1 ? '已设置' : '未设置'
}

const entry_list_1 = computed(() => [
  {
    title: '实名认证',
    action: () => {
      // DEFAULT '2' COMMENT '是否实名认证  1 成功   2待审核   3 拒绝请重新认证  4禁止认证',
      if ([0, 1, 2, 3].includes(authStore?.userInfo?.verified_status)) {
        router.push('verify')
      } else {
        showInfoToast(verifyStatusText().text)
      }
    },
    status_text: verifyStatusText(),
    is_finished: false,
    icon: 'verify-icon'
  }
])

const entry_list_2 = computed(() => [
  {
    title: '银行卡',
    action: () => {
        router.push('bank_card')
    },
    status_text: bankCardStatusText(bind_bank.value),
    is_finished: false,
    icon: 'bank-card-icon'
  },
  {
    title: '微信支付',
    action: () => {
        router.push('wechat')
    },
    status_text: bankCardStatusText(bind_wechat.value),
    is_finished: false,
    icon: 'wechat-icon'
  },
  {
    title: '支付宝',
    action: () => {
        router.push('alipay')
    },
    status_text: bankCardStatusText(bind_alipay.value),
    is_finished: false,
    icon: 'alipay-icon'
  }
])

const entry_list_3 = computed(() => [
  {
    title: '支付密码',
    action: () => {
      router.push('pay_password')
    },
    status_text: payPassStatusText(authStore.userInfo.is_set_paypassword),
    is_finished: false,
    icon: 'shield-icon'
  }
])

const entry_list_4 = [
  {
    title: '信誉评分',
    action: () => {
      router.push('credit')
    },
    status_text: '',
    is_finished: false,
    icon: 'about-icon',
    img_src: creditImg
  },
  {
    title: '关于我们',
    action: () => {
      router.push('about_us')
    },
    status_text: '',
    is_finished: false,
    icon: 'about-icon'
  }
]

const goFundingDetails = () => {
  if (!isLogin) {
    router.push('/auth/login')
  } else {
    router.push('/details/funding-details')
  }
}

// const avatarImg = ref('')

const afterRead = async (event: any) => {
  if (!event.target.files[0]) return
  const res = await uploadImg(event.target.files[0])
  await updateUserInfoApi({
    headimg: res?.img
  })
  authStore?.getUserInfo()
  event.target.value = ''
  // avatarImg.value = res?.img
}
const uploadImg = async (file: string): Promise<any> => {
  try {
    const res = await uploadImgApi({
      file,
      type: 'face'
    })

    return res
  } catch (e) {
    console.log(e)
  }
}

const dialog = reactive({
  show: false,
  data: {} as IMessage
})
// 标记站内信弹窗信息已读
const signMsgReadStatus = async () => {
  try {
    const res = await userMessageDetailsApi({
      id: +dialog.data?.id ?? ''
    })
  } catch (error) {
    console.error(error)
  }
}

// 站内信未读数量
const unReadCount = ref(0)
// 获取站内信弹窗通知内容
const getDialogMessage = async () => {
  try {
    const res = await userMessageListApi({})

    if (!res.count || !res.un_read) {
      return
    }

    unReadCount.value = res?.un_read ?? 0

    const data = res.list.find(item => item.is_openwin === 1 && item.is_read === 0)

    if (data) {
      dialog.data = data
      dialog.show = true

      signMsgReadStatus()
    }

    window.log('消息列表', res)
  } catch (error) {
    console.error(error)
  }
}

const onCloseDialog = () => {
  dialog.show = false
}
// const onClose = () => {
//   dialogContent.show = false
// }

const edit_nickname = ref('')
const isEditNicknameDialog = ref(false)
const handleEditNicknameDialog = (open: boolean) => {
  if (authStore?.editreview?.nickname?.status === -1) {
    showInfoToast('昵称正在审核中请等待')
  } else {
    isEditNicknameDialog.value = open
  }
}

const editNickname = async () => {
  try {
    if (edit_nickname.value.length >= 3 && edit_nickname.value.length <= 8) {
      await updateUserInfoApi({
        nickname: edit_nickname.value
      })
      authStore?.getUserInfo()
    } else {
      edit_nickname.value = ''
      showInfoToast('昵称限制3-8位长度')
    }
  } catch (e) {
    console.log(e)
  } finally {
    handleEditNicknameDialog(false)
    edit_nickname.value = ''
  }
}

onMounted(() => {
  getMineInfo()
  bind_bank.value = coin?.withdrawddresslist.filter(address => address.coin_protocol === 'BANK')[0]
  bind_wechat.value = coin?.withdrawddresslist.filter(
    address => address.coin_protocol === 'WXPAY'
  )[0]
  bind_alipay.value = coin?.withdrawddresslist.filter(
    address => address.coin_protocol === 'ALIPAY'
  )[0]

  getWithdrawddresslist({}).then(() => {
    if (coin?.withdrawddresslist.filter(address => address.coin_protocol === 'BANK').length > 0) {
      bind_bank.value = coin?.withdrawddresslist.filter(
        address => address.coin_protocol === 'BANK'
      )[0]
    }

    if (coin?.withdrawddresslist.filter(address => address.coin_protocol === 'WXPAY').length > 0) {
      bind_wechat.value = coin?.withdrawddresslist.filter(
        address => address.coin_protocol === 'WXPAY'
      )[0]
    }
    if (coin?.withdrawddresslist.filter(address => address.coin_protocol === 'ALIPAY').length > 0) {
      bind_alipay.value = coin?.withdrawddresslist.filter(
        address => address.coin_protocol === 'ALIPAY'
      )[0]
    }
  })
})
</script>

<style lang="scss" scoped>
@import '@/assets/styles/sprite-home.scss';
@import '@/assets/styles/sprite-mine.scss';

.mine {
  position: relative;
  flex-direction: column;
  width: 100%;
  height: 100%;

  :deep(.dialog-msg) {
    width: 708px;
    height: auto;
    padding: 40px;

    .van-dialog__header {
      padding: 0;
      font-size: 29px;
      color: #13161b;
      font-weight: normal;
    }

    .van-dialog__content {
      margin: 33px 0 35px 0;
      font-size: 25px;
      color: #787f8c;
      text-align: justify;
    }

    .van-dialog__footer {
      padding: 0;
    }

    .van-dialog__confirm,
    .btn-confirm {
      width: 100%;
      height: 80px;
      font-size: 31px;
      background: #0b75ff;
      color: #fff;
      border: 0;
      border-radius: 8px;
    }

    .icon-close {
      position: absolute;
      right: 40px;
      top: 24px;
    }

    .add-time {
      margin-bottom: 25px;
    }

    .content {
      color: #13161b;
    }

    img {
      width: 100%;
      margin-top: 20px;
    }
  }
}

:deep(.dialog-bulletin) {
  width: 708px;
  height: auto;
  padding: 20px 30px 30px 30px;
  border-radius: 10px;

  .van-dialog__header {
    padding: 0;
    font-size: 29px;
    color: #13161b;
  }

  .van-dialog__content {
    margin: 33px 0 35px 0;
    font-size: 25px;
    color: #787f8c;
    text-align: justify;
  }

  .van-dialog__footer {
    padding: 0;
  }

  .van-dialog__confirm {
    width: 100%;
    height: 80px;
    font-size: 31px;
    background: #0b75ff;
    border-radius: 8px;
    border-width: 0;
  }

  .icon-close {
    position: absolute;
    right: 40px;
    top: 35px;
  }

  img {
    width: 100%;
    margin-top: 20px;
  }

  .van-cell {
    padding: 0;
  }
}

:deep(.van-cell__value) {
  height: 69px;
  background: #ebf1f6;
  display: flex;
  align-items: center;
  padding: 0 12px;
  font-size: 25px;
  margin-bottom: 12px;
}

:deep(.dialog-deal) {
  width: 708px;
  height: auto;
  padding: 40px;

  .van-dialog__header {
    padding: 0;
    font-size: 29px;
    color: #13161b;
  }

  .van-dialog__content {
    margin: 33px 0 35px 0;
    font-size: 25px;
    color: #787f8c;
    text-align: justify;
  }

  .van-dialog__footer {
    padding: 0;
  }

  .van-dialog__confirm,
  .btn-confirm {
    width: 100%;
    height: 80px;
    font-size: 31px;
    background: #0b75ff;
    color: #fff;
    border: 0;
    border-radius: 8px;
  }

  .dialog-radio-controler {
    margin-top: 20px;

    .radio {
      margin-right: 10px;
    }

    .radio-uncheck {
      width: 35px;
      height: 35px;
      border: 1px solid #868d9a;
      border-radius: 50%;
    }

    .radio-text {
      font-size: 25px;
      color: #13161b;
    }
  }

  .icon-close {
    position: absolute;
    right: 40px;
    top: 24px;
  }

  img {
    width: 100%;

    &.verifi-id {
      width: 260px;
    }

    &.add-card {
      width: 295px;
    }
  }

  .content {
    width: 380px;
    margin-top: 24px;
  }
}

.topbar-container {
  width: 100%;
  flex: 0 0 264px;
  padding: 0 30px 30px 30px;
  box-sizing: border-box;
  background-color: #0b75ff;

  .topbar-content-view {
    position: relative;
    width: 100%;
    height: 90px;

    .logo-container {
      position: absolute;
      top: 48px;
      left: 50%;
      transform: translate3d(-50%, 0, 0);
      display: flex;
      justify-content: space-between;
      align-items: center;

      .home-top-logo {
        width: 45px;
      }

      .text-logo {
        margin-left: 10px;
        margin-top: -7px;
        font-size: 42px;
        color: #fff;
      }
    }

    .help {
      margin: 0 28px;
    }

    .message {
      position: relative;
      margin-bottom: -3px;
      margin-right: auto;
    }

    .unread-sign {
      position: absolute;
      top: -7px;
      right: -9px;
      width: 24px;
      height: 24px;
      line-height: 24px;
      background-color: red;
      color: #fff;
      font-size: 14px;
      text-align: center;
      border-radius: 50%;
    }
  }
}
</style>
<style lang="css">
:root {
  --van-field-placeholder-text-color: #787f8c;
}
</style>

// react_/src/pages/Mine/index.tsx
import { useState, useEffect } from 'react';
import { Column, Row } from '@/components/flex';
import { styled } from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/store';
import { ICoin } from '@/store/types/coin';
import { tokenSelector, logout, userInfoSelector, userCoinsSelector, editreviewSelector } from '@/store/slices/auth.slice';
import { getUserInfoThunk, getUserCoinsThunk } from '@/store/actions/user.thunk';
import { updateUserInfoApi, updateUserInfoParams } from '@/apis/user';
import { useAvatar, useInviteURL } from '@/hooks/user.hooks';
import { useNavigate } from 'react-router-dom';
import MyImg from '@/components/MyImg';
import ShareDialog from './components/ShareDialog';
// import VerifyDialog from './components/VerifyDialog';
import EditNameModal from './components/EditNameModal';
import EntryRow from './components/EntryRow';
import EntryRowGroup from './components/EntryRowGroup';
import { TopBarContainer, ProfileContainer, MineContentContainer } from './mine.styled';
import { spriteMineCss } from '@/components/Sprite';
import { uploadImgApi } from '@/apis/common';
import Toast from '@/utils/toast';

// const IconTutorialColumn = styled(Column)`
//   margin: 0 auto;
//   margin-right: 28rem;
// `;

const MineContainer = styled(Column)`
  width: 100%;
  height: 100%;
  background-color: #ebf1f6;
  overflow: auto;

  /* 精灵图 */
  ${spriteMineCss as any}
`;

const ModalContainer = styled(Column)`
  width:100%;
  height:100rem;
  background-color: #009;
`;

export const TopBarContentView = styled(Row)`
  width: 100%;
  height: 90rem;
  position: relative;

  .icon-customer-service {
    width: 38rem;
    height: 34rem;
  }
  .top-bar-title {
    width: 100%;
    text-align: center;
    color: white;
    font-size: 44rem;
    position: absolute;
    top: 40rem;
    left: 50%;
    transform: translate3d(-50%, 0, 0);
  }
  .icon-help {
    width: 33rem;
    height: 33rem;
    margin: 0 auto;
    margin-right: 28rem;
  }
  .icon-message {
    width: 37rem;
    height: 37rem;
    margin-bottom: -3rem;
  }
`;

const topBarItemList = [
  {
    src: '/files/home/customer-service.png',
    routePath: '/linkPage/customerService',
    className: 'icon-customer-service'
  },
  {
    src: '/files/home/homeLogo.png',
    routePath: '',
    className: 'icon-home-logo',
    text: '我的'
  },
  {
    src: '/files/home/help.png',
    routePath: '/linkPage/tutorial',
    className: 'icon-help'
  },
  {
    src: '/files/home/message.png',
    routePath: '/message',
    className: 'icon-message'
  }
];

const TopBar = () => {
  const navigate = useNavigate();
  const to = (path: string) => { navigate(path); };

  return (
    <TopBarContentView justify="space-between" align="flex-end">
      {
        topBarItemList.map((item) => {
          return (
            item.text
              ? <div className="top-bar-title" key={item.src}>
                {item.text}
              </div>
              : <MyImg
                key={item.src}
                className={item.className}
                src={item.src}
                onClick={() => { to(item.routePath); }}
              />
          );
        })
      }
    </TopBarContentView>
  );
};

const Mine = () => {
  const navigate = useNavigate();
  const token = useAppSelector(tokenSelector);
  const userInfo = useAppSelector(userInfoSelector);
  const editreview = useAppSelector(editreviewSelector);
  const userCoins = useAppSelector(userCoinsSelector);
  const dispatch = useAppDispatch();
  
  const avatar = useAvatar();
  const out = () => {
    dispatch(logout(null));
    navigate('/auth/login');
  };

  const to = (path: string) => { navigate(path); };

  const [isShowShareDialog, setIsShowShareDialog] = useState(false);

  const handleShareDialog = (isShow: boolean) => {
    setIsShowShareDialog(isShow);
  };

  const [isShowEditNameModal, setIsShowEditNameModal] = useState(false);
  const handleEditNameModal = (isShow: boolean) => {
    setIsShowEditNameModal(isShow);
  };

  const uploadImg = async (file: string, type: string): Promise<any> => {
    try {
      const res = await uploadImgApi({
        file,
        type
      });
  
      return res;
    } catch (e) {
      console.log(e);
    }
  };

  const [currentCoin, setCurrentCoin] = useState<ICoin>({
    mtype: 0,
    coin_name: '',
    coin_unit: '',
    coincash: '',
    available_coincash: '',
    status: 0,
    wallet_type: '',
    service_fee: ''
  });

  const updateAvatar = async (event: any) => {
    const res = await uploadImg(event.target.files[0], 'face');

    await updateUserInfo({ headimg: res?.img });
    getUserInfo();
  };

  const getUserInfo = async () => {
    try {
      await dispatch(getUserInfoThunk.asyncThunk());
      console.log(userInfo);
      await dispatch(getUserCoinsThunk.asyncThunk());
      const coin = userCoins.filter(coin => coin?.coin_unit === 'GDB')?.[0];
      
      setCurrentCoin(coin);

      console.log(editreview, 'editreview');
    } catch (e) {
      console.log(e);
    }
  };

  const updateUserInfo = async (params: updateUserInfoParams) => {
    try {
      await updateUserInfoApi(params);
    } catch (e) {
      console.log(e);
    }
  };

  const updateUserName = async (name: string) => {
    try {
      await updateUserInfo({ nickname: name });
    } catch (e) {
      console.log(e);
    }
  };

  const handleShowEditModal = () => {
    if (editreview.nickname.status === -1 ) {
      Toast.show('暱称正在审核中，请等待');

      return;
    }

    setIsShowEditNameModal(true);
  };

  useEffect(() => {
    getUserInfo();
  }, []);

  return (
    <MineContainer>
      {
        isShowShareDialog && <ShareDialog handleDialog={handleShareDialog} />
      }
      {/* <img src={`${process.env.REACT_APP_STATIC_PATH}/files/home/1.png`} alt="" /> */}
      <TopBarContainer>
        <TopBar />
        <ProfileContainer>
          <div className="flex">
            <div className="avatar">
              <MyImg src={avatar} alt='avatar' loading={false} />
              <div className="camera-mask">
                <MyImg src='/files/mine/camera.png' alt='camera' loading={false} />
              </div>
              <input className="avatar-input" type="file" accept="image/*" onChange={updateAvatar} />
              {
                editreview?.headimg?.status === -1 && <div className="input-overlay" onClick={() => Toast.show('头像正在审核中，请等待')}></div>
              }
            </div>
            <div className="info">
              <div className="name">
                {userInfo?.nickname}
                <div className="edit" onClick={handleShowEditModal}></div>
                {/* <MyImg src='/files/mine/edit.png' alt='edit' loading={false} /> */}
              </div>
              <div className="id">{userInfo?.open_id}</div>
            </div>
          </div>
          <div className="right">
            <div className="amount flex">
              余额
              <MyImg className="chervon-icon" src='/files/mine/white-chervon-right.png' alt='verify' loading={false} />
            </div>
            <div className="money">
              <span>{currentCoin?.coincash}</span>{currentCoin?.coin_unit}
            </div>
          </div>
        </ProfileContainer>
      </TopBarContainer>
      <MineContentContainer>
        <EntryRow action={() => { to('/realVerify'); }} title="实名认证" icon="verify-icon" statusType='verify' isDone={userInfo?.verified_status === 1} hasLine={false} />
        <EntryRowGroup title="收款及支付方式">
          <EntryRow action={() => { to('bank'); }} title="银行卡" icon="bank-card-icon" statusType='bind' isDone={true} hasLine={true} />
          <EntryRow action={() => { to('wechat'); }} title="微信支付" icon="wechat-icon" statusType='bind' isDone={false} hasLine={true} />
          <EntryRow action={() => { to('alipay'); }} title="支付宝" icon="alipay-icon" statusType='bind' isDone={true} hasLine={false} />
        </EntryRowGroup>
        <EntryRowGroup title="账号安全">
          <EntryRow action={() => { to('loginPassword'); }} title="登录密码" icon="lock-icon" statusType='bind' isDone={true} hasLine={true} />
          <EntryRow action={() => { to('payPassword'); }} title="支付密码" icon="shield-icon" statusType='bind' isDone={userInfo?.is_set_paypassword === 1} hasLine={true} />
          <EntryRow action={() => { to('email'); }} title="电子邮箱" icon="email-icon" statusType='bind' isDone={userInfo?.is_email_verify === 1} hasLine={true} />
          <EntryRow action={() => { to('device'); }} title="我的设备" icon="device-icon" statusType='bind' isDone={userInfo?.is_sms_verify === 1} hasLine={true} iconIsTall={true} />
          <EntryRow action={() => { handleShareDialog(true); }} title="分享GDPay" icon="share-icon" statusType='none' hasLine={true} iconIsTall={true} />
          <EntryRow action={() => { to('aboutUs'); }} title="关于我们" icon="about-icon" statusType='none' hasLine={true} />
          <EntryRow title="关于我们" icon="check-icon" statusType='bind' isDone={true} hasLine={false} isVersion={true} />
        </EntryRowGroup>
      </MineContentContainer>
      <div>
        <div>用户名:{userInfo?.username}</div>
      </div>
      {token ? <div>已登录,token为:{token}</div> : ''}
      <button onClick={out}>退出登录</button>
      {
        isShowEditNameModal && <EditNameModal handleDialog={handleEditNameModal} submit={updateUserName}></EditNameModal>
      }
    </MineContainer>
  );
};

export default Mine;
