// react_/src/pages/Home/components/Bulletin.tsx
import { Column, Row } from '@/components/flex';
import { styled } from 'styled-components';
import { articleListApi } from '@/apis/article';
import React, { useState, useEffect } from 'react';
import Marquee from '@/components/Marquee';
import IModal from '@/components/IModal';
import { StateProps } from '@/pages/Home/types';
import { IArticleListType } from '@/store/types/article';
import ISprite from '@/components/ISprite';
const BulletinContainer = styled(Row)`
  width: 100%;
  height: 50rem;
  margin: 10rem 0;
  font-size: 26rem;
  .icon-bulletin {
    margin-right: 10rem;
  }
  .marquee {
    height: 50rem;
  }
  .item-notice {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    height: 50rem;
    margin-bottom: 20rem;
  }
`;
const ModalContentContainer = styled(Column)`
  width: 90%;
  margin: 0 auto;
  background-color: #fff;
  .title {
    margin-top: 35rem;
    font-size: 29rem;
    color: #13161b;
  }
  .content {
    margin: 33rem 0 35rem 0;
    font-size: 25rem;
    color: #787f8c;
    text-align: justify;
    img {
      width: 100%;
      margin-top: 20rem;
    }
  }
`;
const Bulletin = () => {
  const [noticeData, setNoticeData] = useState<any[]>([]);
  const [visible, setVisible] = useState(false);
  const [modalObj, setModalObj] = useState<StateProps>({
    title: '',
    content: ''
  });
  const bulletinCssProps = {
    url: '/sprites/home/sprite-home.png',
    backgroundSize: [323, 261],
    originSize: [45, 33],
    size: [32, 24],
    pos: [-242, -140]
  };

  const NoticeView = (data: any[]) => {
    const openNotice = (notice: IArticleListType) => {
      setModalObj({
        title: notice.title,
        content: notice.content
      });
      setVisible(true);
    };

    return data.map((item, index) => {
      return (
        <div className='item-notice' key={index} onClick={() => { openNotice(item); }}>
          {item.title}
        </div>
      );
    });
  };
  const handleRollingNoticeData = async () => {
    try {
      const res = await articleListApi({
        bind_key: 'RollingNotice'
      });

      if (res.length) {
        setNoticeData(NoticeView(res));
      }

      window.log('滚动公告内容', res);
    } catch (error) {
      console.error(error);
    }
  };
  const onClose = () => {
    setVisible(false);
  };
  const CloseBtn = () => {
    return (
      <div className='close-dark'></div>
    );
  };

  useEffect(() => {
    handleRollingNoticeData();
  }, []);
  
  return (
    <BulletinContainer align="center">
      <ISprite {...bulletinCssProps} className='icon-bulletin' />
      {noticeData.length && <Marquee list={noticeData} />}
      <IModal
        visible={visible}
        onClose={onClose}
        CloseBtn={CloseBtn}
        onCheck={(e: boolean) => { console.log('e', e); }}
        submit={{
          name: '提交',
          async onClick() {
            onClose();
          }
        }}>
        <ModalContentContainer>
          <div className="title">{modalObj.title}</div>
          <div className="content" dangerouslySetInnerHTML={{ __html: modalObj.content }}></div>
        </ModalContentContainer>
      </IModal>
    </BulletinContainer>
  );
};

export default Bulletin;

// src/components/Home/Bulletin.vue
<script setup lang="ts">
import { articleListApi } from '@/apis/article'
import { useArticleStore } from '@/store/modules/article'
import { useAuthStore } from '@/store/modules/auth'
import { IArticleListType } from '@/store/types/article'
import { storeToRefs } from 'pinia'
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'

const authStore = useAuthStore()
const { token, userInfo } = storeToRefs(authStore)
const { cash } = userInfo.value

const router = useRouter()
const articleStore = useArticleStore()
const { getArticleListApi } = articleStore
const { rollingNotice } = storeToRefs(articleStore)

const bulletinData = ref<IArticleListType[]>([])

const isLogin = computed(() => !!token.value)

const emit = defineEmits(['update-article'])

const handleRollingNoticeData = async () => {
  try {
    let res: IArticleListType[] = await getArticleListApi({
      bind_key: 'OpenNotice,RollingNotice,HomeHuanDeng'
    })

    emit('update-article')
    // res = rollingNotice.value

    // if (res.length) {
    //   bulletinData.value = res
    // }

    window.log('跑马灯公告内容', res)
  } catch (error) {
    console.error(error)
  }
}

const dialogShow = ref(false)
const dialog = ref<IArticleListType | Record<string, any>>({})

const handleShowDialog = (_dialog: IArticleListType) => {
  dialog.value = _dialog
  dialogShow.value = true
}
const closeDialog = () => {
  dialogShow.value = false
}

onMounted(() => {
  handleRollingNoticeData()
})
</script>

<template>
  <div class="bulletin-container flex items-center">
    <div class="bulletin"></div>
    <van-swipe
      autoplay="4000"
      duration="600"
      vertical
      :show-indicators="false"
      :touchable="false"
      class="swipe-bulletin"
    >
      <van-swipe-item
        v-for="item in rollingNotice"
        :key="item.id"
        @click="handleShowDialog(item)"
      >
        <div v-html="item.title"></div>
      </van-swipe-item>
    </van-swipe>

    <van-dialog
      v-model:show="dialogShow"
      title="公告"
      confirmButtonText="我知道了"
      theme="round-button"
      className="dialog-bulletin"
    >
      <i
        class="icon-close close-dark block"
        @click="closeDialog"
      ></i>
      <div v-html="dialog.content"></div>
    </van-dialog>
  </div>
</template>

<style lang="scss" scoped>
@import '@/assets/styles/sprite-home.scss';
.bulletin-container {
  position: relative;
  width: 100%;
  height: 50px;
  margin: 10px 0;
  font-size: 26px;
  .bulletin {
    margin-right: 10px;
  }
  :deep(.swipe-bulletin) {
    height: 50px;
    line-height: 50px;
    overflow: hidden;
    .van-swipe__track {
      transition-timing-function: linear;
    }
  }
  :deep(.dialog-bulletin) {
    width: 708px;
    height: auto;
    padding: 40px;
    .van-dialog__header {
      padding: 0;
      font-size: 29px;
      color: #13161b;
    }
    .van-dialog__content {
      margin: 33px 0 35px 0;
      font-size: 25px;
      color: #787f8c;
      text-align: justify;
    }
    .van-dialog__footer {
      padding: 0;
    }
    .van-dialog__confirm {
      width: 100%;
      height: 80px;
      font-size: 31px;
      background: #0b75ff;
      border-radius: 8px;
      border-width: 0;
    }
    .icon-close {
      position: absolute;
      right: 40px;
      top: 24px;
    }
    img {
      width: 100%;
      margin-top: 20px;
    }
  }
  .marquee {
    height: 50px;
  }
  .item-notice {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    height: 50px;
    margin-bottom: 20px;
  }
}
</style>
