// react_/src/pages/Home/components/DealInfo.tsx
import { Column, Row } from '@/components/flex';
import { styled } from 'styled-components';
import { useAppSelector } from '@/store';
import { tokenSelector } from '@/store/slices/auth.slice';
import { buySellCoinInfoApi } from '@/apis/buySellCoin';
import { useEffect, useState } from 'react';
const DealInfoContainer = styled(Row)`
  width: 100%;
  height: 140rem;
  margin: 17rem 0;
  background-color: #fff;
  border-radius: 14rem;
  .deal-info-item {
    position: relative;
    flex: 1;
    justify-content: center;
    height: 100rem;
    color: #868d9a;
    &.hairline-border::after {
      border: 0 !important;
      border-left: 1px solid #d6dce8 !important;
      border-right: 1px solid #d6dce8 !important;
    }
    .item-amount {
      margin-right: 5rem;
      font-size: 31rem;
      color: #13161b;
    }
    .item-GDB {
      font-size: 28rem;
    }
    .item-title {
      font-size: 26rem;
    }
  }
`;

const GDB = 'GDB';
const DealInfo = () => {
  const token = useAppSelector(tokenSelector);
  const [DealInfoItemList, setDealInfoItemList] = useState(
    [
      {
        id: 1,
        title: '卖单金额',
        amount: 0.00
      },
      {
        id: 2,
        title: '买币交易中',
        amount: 0.00
      },
      {
        id: 3,
        title: '卖币交易中',
        amount: 0.00
      }
    ]
  );
  const mType = 5;
  const getBuySellCoinInfo = async () => {
    try {
      const res = await buySellCoinInfoApi({
        token,
        mtype: mType
      });
  
      if (res) {
        const data = res.wallets[mType];
  
        window.log('买卖币资讯', res);
  
        setDealInfoItemList([
          {
            id: 1,
            title: '卖单金额',
            amount: data.remaining_num
          },
          {
            id: 2,
            title: '买币交易中',
            amount: data.trans.buy
          },
          {
            id: 3,
            title: '卖币交易中',
            amount: data.trans.sell
          }
        ]);
      }
    } catch (error) {
      console.log('error', error);
    }
  };

  useEffect(() => {
    getBuySellCoinInfo();
  }, []);
  
  return (
    <DealInfoContainer align="center">
      {
        DealInfoItemList.map((item) => {
          const className = item.id === 2 ? 'deal-info-item hairline-border' : 'deal-info-item';

          return (
            <Column key={item.id} className={className}>
              <div>
                <span className='item-amount'>{item.amount.toFixed(2)}</span>
                <span className='item-GDB'>{GDB}</span>
              </div>
              <div className='item-title'>{item.title}</div>
            </Column>
          );
        })
      }
    </DealInfoContainer>
  );
};

export default DealInfo;

// src/components/Home/DealInfo.vue
<script setup lang="ts">
import { articleListApi } from '@/apis/article'
import { buySellCoinInfoApi } from '@/apis/buySellCoin'
import { useAuthStore } from '@/store/modules/auth'
import { useCoinBuySellStore } from '@/store/modules/coinBuySell'
import { IArticleListType } from '@/store/types/article'
import { storeToRefs } from 'pinia'
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import mitt from '@/utils/mitt'

const authStore = useAuthStore()
const { userInfo, token } = storeToRefs(authStore)
const router = useRouter()

const coinBuySellStore = useCoinBuySellStore()
const { getBuySellCoinInfo } = coinBuySellStore
const { dealInfo } = storeToRefs(coinBuySellStore)

const mType = 1
const dealInfoItemList = ref([
  {
    id: 1,
    title: '卖单金额',
    amount: dealInfo.value.wallets?.[mType]?.remaining_num ?? 0.0
  },
  {
    id: 2,
    title: '买币交易中',
    amount: dealInfo.value.wallets?.[mType]?.trans?.buy ?? 0.0
  },
  {
    id: 3,
    title: '卖币交易中',
    amount: dealInfo.value.wallets?.[mType]?.trans?.sell ?? 0.0
  }
])

const getBuySellCoinInfoData = async () => {
  try {
    const res = await getBuySellCoinInfo({
      mtype: mType
    })

    if (res) {
      const data = res.wallets[mType]

      window.log('买卖币资讯', res)

      dealInfoItemList.value = [
        {
          id: 1,
          title: '卖单金额',
          amount: data.remaining_num
        },
        {
          id: 2,
          title: '买币交易中',
          amount: data.trans.buy
        },
        {
          id: 3,
          title: '卖币交易中',
          amount: data.trans.sell
        }
      ]
    }
  } catch (error) {
    console.log('error', error)
  }
}

onMounted(() => {
  getBuySellCoinInfoData()

  mitt.on('push_coin_buy_order_status', getBuySellCoinInfoData)
  mitt.on('push_coin_sell_order_status', getBuySellCoinInfoData)
})
onUnmounted(() => {
  mitt.off('push_coin_buy_order_status', getBuySellCoinInfoData)
  mitt.off('push_coin_sell_order_status', getBuySellCoinInfoData)
})
</script>

<template>
  <div class="deal-info-container flex items-center">
    <div
      v-for="item in dealInfoItemList"
      :key="item.id"
      class="flex flex-col justify-center items-center"
      :class="item.id === 2 ? 'deal-info-item hairline-border' : 'deal-info-item'"
    >
      <div class="flex items-center justify-center">
        <span class="item-amount">{{ item.amount.toFixed(2) }}</span>
        <span class="item-GDB">GDB</span>
      </div>
      <div class="item-title">{{ item.title }}</div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.deal-info-container {
  width: 100%;
  height: 140px;
  margin: 17px 0;
  background-color: #fff;
  border-radius: 14px;
  .deal-info-item {
    position: relative;
    flex: 1;
    justify-content: center;
    height: 100px;
    color: #868d9a;
    &.hairline-border::after {
      border: 0 !important;
      border-left: 1px solid #d6dce8 !important;
      border-right: 1px solid #d6dce8 !important;
    }
    .item-amount {
      margin-right: 5px;
      font-size: 31px;
      color: #13161b;
    }
    .item-GDB {
      font-size: 28px;
    }
    .item-title {
      font-size: 26px;
    }
  }
}
</style>
