// src/components/Point/LuckyDraw.vue
<script setup lang="ts">
import { useTaskActivityStore } from '@/store/modules/taskActivity'
import { useCommonStore } from '@/store/modules/common'
import {
  IAwardData,
  IGameRecord,
  IGameRecordData,
  IPlayTurntableData,
  ITurntableAward,
  ITurntableOption
} from '@/store/types/taskActivity'
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import dayjs from 'dayjs'
import noData from '@/assets/images/common/noData-gold.png'
import { storeToRefs } from 'pinia'
import { showToast } from 'vant'
import iconWarning from '@/assets/images/common/warning.png'
import { Vue3SeamlessScroll as SeamlessScroll } from 'vue3-seamless-scroll'
import { useAuthStore } from '@/store'
import { useEntryStore } from '@/store/modules/entry'
import { INormal } from '@/store/types/entry'
import currency from 'currency.js'

const emit = defineEmits(['update-coins'])

type TTurntableAward = Partial<ITurntableAward>

// 抽奖记录
const winRecordList = ref<IGameRecord[]>([])
// 抽奖轮盘奖项列表
const awardLoopList = ref<TTurntableAward[]>([
  {
    class: 'RMB-4'
  },
  {
    class: 'point-1'
  },
  {
    class: 'RMB-gold-box'
  },
  {
    class: 'lucky-star'
  },
  {
    class: 'point-5'
  },
  {
    class: 'point-8'
  },
  {
    class: 'RMB-1'
  },
  {
    class: 'RMB-silver-box'
  },
  {
    class: 'point-3'
  },
  {
    class: 'RMB-3'
  }
])
interface IAwardState {
  currentIndex: number // 当前位置
  isRunning: boolean // 是否正在抽奖
  speed: number // 抽奖转动速度
  runTurnTableTimer: NodeJS.Timeout | null // 抽奖轮盘计时器
  turnTableLimitTimer: NodeJS.Timeout | null // 抽奖频率计时器
  currentRunCount: number // 已跑次数
  totalRunCount: number // 总共跑动次数 10的倍数
  prizeId: number // 中奖id
  continue: number // 是否可以继续抽奖
}
// 抽奖相关数据状态
const awardState = reactive<IAwardState>({
  currentIndex: -1, // 当前位置
  isRunning: false, // 是否正在抽奖
  speed: 10, // 抽奖转动速度
  runTurnTableTimer: null, // 抽奖轮盘计时器
  turnTableLimitTimer: null, // 抽奖频率计时器
  currentRunCount: 0, // 已跑次数
  totalRunCount: 40, // 总共跑动次数 10的倍数
  prizeId: 0, // 中奖id
  continue: 1 // 是否可以继续抽奖
})
const awardResult = reactive<IPlayTurntableData>({
  awards: [],
  mtype: {
    '0': 0,
    '1': 0,
    '20': 0
  }
})
// 奖品高亮顺序
const prizeSort = [0, 1, 2, 3, 4, 9, 8, 7, 6, 5, 0]
// 抽奖按钮
const btnList = ref<ITurntableOption[]>([])

const entryStore = useEntryStore()
const { config } = storeToRefs(entryStore)

const appDomain = computed(() => {
  return (config.value.Web_Set_DefaultInfo?.imgserver_url as INormal).v || ''
})

const taskActivityStore = useTaskActivityStore()
const { getTurntableAwardsApi, getGameRecordApi, getPlayTurntableApi } = taskActivityStore
const { turntableAwards, awardRecord } = storeToRefs(taskActivityStore)

const handleTurnTableAwardsData = (data: IAwardData) => {
  awardLoopList.value = data.awards
  btnList.value = data.options
}
// 获取轮盘奖项列表
const getTurntableAwards = async () => {
  try {
    let res: IAwardData = turntableAwards.value

    if (!res.awards?.length) {
      res = await getTurntableAwardsApi()
    }

    handleTurnTableAwardsData(res)

    window.log('轮盘奖项列表', res)
  } catch (error) {
    console.error(error)
  }
}
// 获取抽奖记录
const getGameRecord = async (isReq: boolean = false) => {
  try {
    let res: IGameRecordData

    if (awardRecord.value.count && !isReq) {
      res = awardRecord.value
    } else {
      res = await getGameRecordApi()
    }

    if (res.list?.length) {
      winRecordList.value = res.list
    }

    window.log('抽奖记录', res)
  } catch (error) {
    console.error(error)
  }
}

// 要执行总步数
const totalRunStep = computed(() => {
  return awardState.totalRunCount + prizeSort.indexOf(awardState.prizeId)
})

// 获取随机数
const getRandomNum = () => {
  // 这里一次必然可以取到 时间为1次
  return prizeSort[Math.floor(Math.random() * prizeSort.length)]
}

const authStore = useAuthStore()
const { getUserMoneyByMType } = storeToRefs(authStore)
// 点击抽奖
const runTurntable = (item: ITurntableOption) => {
  const point = +(getUserMoneyByMType.value(20)?.coincash ?? 0)
  if (point < +item.consume) {
    showToast({
      message: '积分不足',
      icon: iconWarning
    })

    return
  }
  if (!awardState.continue) {
    showToast({
      message: '10秒内只能操作一次',
      icon: iconWarning
    })

    return
  }

  if (!awardState.isRunning) {
    // 重置数据
    awardState.currentRunCount = 0
    awardState.speed = 30
    awardState.isRunning = true

    // 如果接口突然报错如何处理？直接调用stopRun()方法停止转动
    getTurnTableData(item.id)
  }
}

const startRun = () => {
  stopRun()
  // window.log('--currentRunCount-totalRunStep--', awardState.currentRunCount, totalRunStep.value)
  // 要执行总步数
  // 已走步数超过
  if (awardState.currentRunCount > totalRunStep.value) {
    awardState.isRunning = false
    showDialog.value = true
    awardState.currentIndex = -1
    emit('update-coins', true)
    getGameRecord(true)
    return
  }
  awardState.currentIndex = prizeSort[awardState.currentRunCount % 10]
  // 如果当前步数超过了2/3则速度慢下来
  if (awardState.currentRunCount > Math.floor((awardState.totalRunCount * 2) / 3)) {
    awardState.speed = awardState.speed + Math.floor(awardState.currentRunCount / 3)
    // console.log('速度>>>>', awardState.speed)
  }
  awardState.runTurnTableTimer = setTimeout(() => {
    awardState.currentRunCount++
    startRun()
  }, awardState.speed)
}

const stopRun = () => {
  awardState.runTurnTableTimer && clearTimeout(awardState.runTurnTableTimer)
}

const commonStore = useCommonStore()
// 轮盘抽奖
const getTurnTableData = async (id: number) => {
  try {
    commonStore.setShowLoading(true)
    awardState.continue = 0

    const params = {
      config_id: id
    }

    const res = await getPlayTurntableApi(params)

    if (res.awards?.length) {
      awardResult.awards = res.awards
      awardResult.mtype = res.mtype

      const prizeId = awardLoopList.value.findIndex(
        item => item.turntable_idd === res.awards[0].turntable_idd
      )

      if (~prizeId) {
        awardState.prizeId = prizeId
        startRun()
      }
    }

    window.log('抽奖', res)
  } catch (error) {
    console.error(error)
  } finally {
    commonStore.setShowLoading(false)

    awardState.turnTableLimitTimer && clearTimeout(awardState.turnTableLimitTimer)
    awardState.turnTableLimitTimer = setTimeout(() => {
      awardState.isRunning = false
      awardState.continue = 1
    }, 10 * 1000)
  }
}

const showDialog = ref(false)

const closeDialog = () => {
  showDialog.value = false
}

onMounted(() => {
  getTurntableAwards()
  getGameRecord()
})
onBeforeUnmount(() => {
  awardState.runTurnTableTimer && clearTimeout(awardState.runTurnTableTimer)
  awardState.runTurnTableTimer = null
  awardState.turnTableLimitTimer && clearTimeout(awardState.turnTableLimitTimer)
  awardState.turnTableLimitTimer = null
})
</script>

<template>
  <div class="lucky-draw-container">
    <div class="draw-middle-container flex items-center">
      <div class="award-loop-container flex items-center flex-wrap">
        <div
          v-for="(item, index) in awardLoopList"
          :key="item.id"
          class="item-award flex flex-col items-center justify-between"
          :class="{ active: awardState.currentIndex === index }"
        >
          <div class="icon-container flex items-center justify-center">
            <img
              v-if="item.activity_img"
              :src="appDomain + item.activity_img"
            />
            <i
              v-else
              :class="item.class"
            ></i>
          </div>
          <div class="award-name">{{ item.turntable_name }}</div>
        </div>
      </div>
      <div class="right-scroll-container">
        <div class="title">中奖记录</div>
        <div
          class="winning-record"
          :class="!winRecordList.length ? 'flex items-center justify-center' : ''"
        >
          <SeamlessScroll
            v-if="winRecordList.length"
            :list="winRecordList"
            :limitScrollNum="7"
            :step="0.3"
            class="seamless-scroll"
          >
            <div
              v-for="(item, index) in winRecordList"
              :key="index"
              class="item-award-history ellipsis"
            >
              {{ dayjs(item.addtime).format('HH:mm') }}中奖{{ item.record_desc }}
            </div>
          </SeamlessScroll>

          <div
            v-else
            class="no-data flex flex-col items-center justify-center text-center"
          >
            <img :src="noData" />
            <div class="text-no-data">暂无数据</div>
          </div>
        </div>
      </div>
    </div>
    <div class="lottery-container flex items-center justify-between">
      <div
        v-for="item in btnList"
        :key="item.id"
        class="award-btn"
        @click="runTurntable(item)"
      >
        <div className="item-name">{{ item.title }}</div>
        <div className="item-required-point">({{ item.consume }}积分)</div>
        <div
          v-if="item.discount"
          class="discount"
        >
          <div className="discount-num">{{ item.discount }}</div>
        </div>
      </div>
    </div>

    <van-dialog
      v-model:show="showDialog"
      theme="round-button"
      confirmButtonText="确定"
      class="point-dialog award-result-dialog"
    >
      <i
        class="close-white block icon-pos"
        @click="closeDialog"
      ></i>
      <div class="title">抽奖结果</div>
      <div class="content">
        <div class="result-summary">
          <div
            v-if="!awardResult.mtype['1'] && !awardResult.mtype['20']"
            class="item-result-title lucky-king"
          >
            {{ awardResult.awards[0]?.turntable_name }}
          </div>
          <template v-else>
            <div
              v-if="awardResult.mtype['20']"
              class="item-result-title"
            >
              <span>获得积分：</span>
              <span class="result-value">+{{ awardResult.mtype['20'] }}</span>
            </div>
            <div
              v-if="awardResult.mtype['1']"
              class="item-result-title"
            >
              <span>获得GDB：</span>
              <span class="result-value">+{{ currency(awardResult.mtype['1']) }}</span>
            </div>
          </template>
        </div>
        <div class="award-list-container flex flex-wrap justify-between">
          <div
            v-for="(item, index) in awardResult.awards"
            :key="index"
            class="item-award flex flex-col justify-center items-center"
          >
            <div class="award-icon"><img :src="appDomain + item.activity_img" /></div>
            <div class="award-name">{{ item.turntable_name }}</div>
          </div>
        </div>
      </div>
    </van-dialog>
  </div>
</template>

<style lang="scss" score>
@import '@/assets/styles/sprite-point.scss';

.lucky-draw-container {
  position: relative;
  width: 100%;
  height: 460px;
  margin: 30px 0;
  background: url('@/assets/images/common/lucky-draw.png') center / cover no-repeat;
  .draw-middle-container {
    position: absolute;
    top: 97px;
    left: 15px;
    width: 680px;
    height: 258px;
    padding: 15px 22px;
    overflow: auto;
    .award-loop-container {
      width: 472px;
      min-width: 472px;
      gap: 13px;
      .item-award {
        width: 84px;
        height: 105px;
        justify-content: space-between;
        padding-bottom: 9px;
        background-color: #fff;
        border-radius: 7px;
        &.active {
          border: 6px solid #57fb07;
        }
        .icon-container {
          height: calc(100% - 28px);
          transform: scale(0.85);
          .RMB-gold-box,
          .RMB-silver-box,
          .lucky-star,
          .point-8 {
            margin-top: 5px;
          }
          img {
            width: 100%;
          }
        }
        .award-name {
          font-size: 19px;
          color: #cf0224;
        }
      }
    }
    .right-scroll-container {
      align-self: flex-start;
      margin-left: 10px;
      color: #fff;
      .title {
        margin-bottom: 10px;
        font-size: 24px;
        color: #ffdae0;
        text-align: left;
      }
      .winning-record {
        // display: block;
        width: 146px;
        height: 180px;
        gap: 20px;
        font-size: 18px;
        color: #fabe73;
        overflow: auto;
        .seamless-scroll {
          height: 180px;
          overflow: hidden;
        }
        .item-award-history {
          width: 100%;
          flex: 0 0 26px;
        }
        .no-data {
          img {
            width: 140px;
            // height: 110px;
          }
          .text-no-data {
            width: 100%;
            margin-bottom: 22px;
            font-size: 12px;
          }
        }
      }
    }
  }
  .lottery-container {
    position: absolute;
    left: 15px;
    bottom: 15px;
    width: calc(100% - 30px);
    height: 80px;
    .award-btn {
      position: relative;
      text-align: center;
      .discount {
        position: absolute;
        top: -18px;
        right: -14px;
        .discount-num {
          position: absolute;
          top: 26px;
          left: 50%;
          transform: translate3d(-50%, -50%, 0);
          font-size: 17px;
          color: #fff;
          white-space: nowrap;
        }
      }
    }
    .item-name {
      font-size: 25px;
      color: #cf0224;
      font-weight: bold;
    }
    .item-required-point {
      font-size: 17px;
      color: #bb7100;
    }
  }

  .award-result-dialog {
    .content {
      padding-top: 17px !important;
      padding-bottom: 17px !important;
      .result-summary {
        padding-bottom: 17px;
        font-size: 25px;
        color: #787f8c;
        border-bottom: 1px solid #d9dde8;
      }
      .result-value {
        margin-left: 16px;
        color: #13161b;
      }
      .award-list-container {
        width: 100%;
        height: 270px;
        padding: 18px 10px 0 10px;
        gap: 15px 0;
        overflow-y: auto;
        .item-award {
          width: 105px;
          height: 105px;
          padding: 5px 0;
          color: #8e8f90;
          background-color: #fff;
          border-radius: 7px;
          .award-icon {
            width: 60%;
            img {
              margin-top: 0;
            }
          }
          .award-name {
            font-size: 22px;
          }
        }
      }
    }
  }
}
</style>

// react_/src/pages/Point/components/LuckyDraw.tsx
import { Row, Column } from '@/components/flex';
import { styled } from 'styled-components';
import { useNavigate } from 'react-router-dom';
const LuckyDrawContainer = styled.div`
  position: relative;
  width: 100%;
  height: 460rem;
  margin: 30rem 0;
  background: url(${`${process.env.REACT_APP_STATIC_PATH}/files/point/lucky-draw.webp`}) center / cover no-repeat;
  .draw-middle-container {
    position: absolute;
    top: 97rem;
    left: 15rem;
    width: 680rem;
    height: 258rem;
    padding: 15rem 22rem;
    .award-loop-container {
      width: 472rem;
      min-width: 472rem;
      gap: 13rem;
      .item-award {
        width: 84rem;
        height: 105rem;
        justify-content: space-between;
        padding-bottom: 9rem;
        background-color: #fff;
        border-radius: 7rem;
        .icon-container {
          height: calc(100% - 28rem);
          transform: scale(0.85);
          .RMB-gold-box, .RMB-silver-box, .lucky-star, .point-8 {
            margin-top: 5rem;
          }
        }
        .award-name {
          font-size: 19rem;
          color: #cf0224;
        }
      }
    }
    .right-scroll-container {
      align-self: flex-start;
      margin-left: 10rem;
      color: #fff;
      .title {
        margin-bottom: 10rem;
        font-size: 24rem;
        color: #ffdae0;
        text-align: left;
      }
      .winning-record {
        width: 146rem;
        height: 166rem;
        gap: 10rem;
        font-size: 18rem;
        color: #fabe73;
        overflow: auto;
        .item-award-history {
          width: 100%;
          flex: 0 0 26rem;
        }
      }
    }
  }
  .lottery-container {
    position: absolute;
    left: 15rem;
    bottom: 15rem;
    width: calc(100% - 30rem);
    height: 80rem;
    .award-btn {
      position: relative;
      .discount {
        position: absolute;
        top: -18rem;
        right: -14rem;
        .discount-num {
          position: absolute;
          top: 26rem;
          left: 50%;
          transform: translate3d(-50%, -50%, 0);
          font-size: 17rem;
          color: #fff;
          white-space: nowrap;
        }
      }
    }
    .item-name {
      font-size: 25rem;
      color: #cf0224;
      font-weight: bold;
    }
    .item-required-point {
      font-size: 17rem;
      color: #bb7100;
    }
  }
`;

const winRecordList = [
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 10,
    type: 1
  },
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 10,
    type: 2
  },
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 10,
    type: 1
  },
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 30,
    type: 2
  },
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 1000,
    type: 1
  },
  {
    userName: 'sdf',
    datetime: '18:30',
    value: 10,
    type: 1
  }
];

const awardLoopList = [
  {
    icon: '/files/point/RMB-10.png',
    className: 'RMB-4',
    value: 10,
    type: 1,
    cssProps: {
      url: '/sprites/point/sprite-point.png',
      backgroundSize: [473, 455],
      originSize: [42, 28],
      size: [30, 20],
      pos: [-289, -380]
    }
  },
  {
    icon: '/files/point/point-10-luck.png',
    className: 'point-1',
    value: 10,
    type: 2
  },
  {
    icon: '/files/point/RMB-jackpot.png',
    className: 'RMB-gold-box',
    value: 8888,
    type: 1
  },
  {
    icon: '/files/point/lucky-star.png',
    className: 'lucky-star',
    value: '福星高照',
    type: 3
  },
  {
    icon: '/files/point/point-50-luck.png',
    className: 'point-5',
    value: 50,
    type: 2
  },
  {
    icon: '/files/point/point-200-luck.png',
    className: 'point-8',
    value: 200,
    type: 2
  },
  {
    icon: '/files/point/RMB-point66.png',
    className: 'RMB-1',
    value: 0.66,
    type: 1
  },
  {
    icon: '/files/point/RMB-666.png',
    className: 'RMB-silver-box',
    value: 666,
    type: 1
  },
  {
    icon: '/files/point/point-3-luck.png',
    className: 'point-3',
    value: 3,
    type: 2
  },
  {
    icon: '/files/point/RMB-6.6.png',
    className: 'RMB-3',
    value: 6.6,
    type: 1
  }
];

const btnList = [
  {
    id: 1,
    name: '单抽',
    requiredPoint: 30,
    discount: 0
  },
  {
    id: 2,
    name: '十连抽',
    requiredPoint: 270,
    discount: 9
  },
  {
    id: 3,
    name: '五十连抽',
    requiredPoint: 1200,
    discount: 8
  }
];
const LuckyDraw = () => {
  const to = useNavigate();
  const onCheckIn = () => {
    
  };

  return (
    <LuckyDrawContainer>
      <Row className='draw-middle-container'>
        <Row className='award-loop-container' wrap='wrap'>
          {
            awardLoopList.map(item => {
              let suffix;

              if (item.type === 1) {
                suffix = '元';
              } else if (item.type === 2) {
                suffix = '积分';
              } else {
                suffix = '';
              }

              return (
                <Column key={item.icon} className='item-award'>
                  <Row justify='center' className='icon-container'>
                    <div className={item.className}></div>
                  </Row>
                  <div className='award-name'>{item.value}{suffix}</div>
                </Column>
              );
            })
          }
        </Row>
        <div className='right-scroll-container'>
          <div className='title'>中奖记录</div>
          <Column className='winning-record' align='flex-start'>
            {
              winRecordList.map(item => {
                const itemKey = item.userName + Math.random().toString();
                let suffix;

                if (item.type === 1) {
                  suffix = '元';
                } else if (item.type === 2) {
                  suffix = '积分';
                } else {
                  suffix = '';
                }

                return (
                  <div key={itemKey} className='item-award-history ellipsis'>{item.datetime}{item.userName}中奖{item.value}{suffix}</div>
                );
              })
            }
          </Column>
        </div>
      </Row>
      <Row className='lottery-container' justify='space-between'>
        {
          btnList.map(item => {
            return (
              <div key={item.id} className='award-btn'>
                <div className='item-name'>{item.name}</div>
                <div className='item-required-point'>({item.requiredPoint}积分)</div>
                {
                  item.discount
                    ? <div className='discount'><div className='discount-num'>{item.discount}折</div></div>
                    : ''
                }
              </div>
            );
          })
        }
      </Row>
    </LuckyDrawContainer>
  );
};

export default LuckyDraw;
